# Generated by Django 3.2.7 on 2022-01-25 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dctr_Name', models.CharField(default='', max_length=300)),
                ('Dctr_Password', models.CharField(default='', max_length=50)),
                ('Dctr_Email', models.CharField(default='', max_length=300)),
                ('Dctr_Phone', models.CharField(default='', max_length=300)),
                ('Dctr_Department', models.CharField(default='', max_length=300)),
                ('Dctr_Place', models.CharField(default='', max_length=300)),
                ('Dctr_Photo', models.ImageField(upload_to='images/')),
                ('Dctr_Fee', models.CharField(default='', max_length=300)),
                ('Type', models.CharField(default='', max_length=300)),
                ('Dctr_Time', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=300)),
                ('MobileNumber', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=300)),
                ('Message', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_Name', models.CharField(default='', max_length=300)),
                ('Pro_Code', models.CharField(default='', max_length=300)),
                ('Pro_Description', models.CharField(default='', max_length=300)),
                ('Pro_Image', models.ImageField(upload_to='product/')),
                ('Pro_Price', models.CharField(default='', max_length=300)),
                ('Pro_Qty', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_Name', models.CharField(default='', max_length=300)),
                ('Shop_Password', models.CharField(default='', max_length=50)),
                ('Shop_Email', models.CharField(default='', max_length=300)),
                ('Shop_Phone', models.CharField(default='', max_length=300)),
                ('Shop_License', models.CharField(default='', max_length=300)),
                ('Shop_Status', models.CharField(default='', max_length=300)),
                ('Shop_Place', models.CharField(default='', max_length=300)),
                ('Shop_Type', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(default='', max_length=300)),
                ('User_Password', models.CharField(default='', max_length=50)),
                ('User_Email', models.CharField(default='', max_length=300)),
                ('User_Address', models.CharField(default='', max_length=300)),
                ('User_District', models.CharField(default='', max_length=20)),
                ('User_Phone', models.CharField(default='', max_length=20)),
                ('User_Type', models.CharField(default='', max_length=20)),
                ('User_Status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Name', models.CharField(default='', max_length=300)),
                ('Staff_Password', models.CharField(default='', max_length=50)),
                ('Staff_Email', models.CharField(default='', max_length=300)),
                ('Staff_Phone', models.CharField(default='', max_length=300)),
                ('Staff_Type', models.CharField(default='', max_length=300)),
                ('Staff_Product_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_product')),
                ('Staff_Shop_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_shops')),
                ('Staff_User_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_user')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='Pro_Shop_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_shops'),
        ),
        migrations.CreateModel(
            name='Tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.CharField(default='', max_length=300)),
                ('total', models.CharField(default='', max_length=300)),
                ('Order_Status', models.CharField(default='', max_length=300)),
                ('status', models.CharField(default='', max_length=300)),
                ('quantity', models.CharField(default='', max_length=300)),
                ('Order_Price', models.CharField(default='', max_length=300)),
                ('Staff_Email', models.CharField(default='', max_length=300)),
                ('Order_Payment_Status', models.CharField(default='', max_length=300)),
                ('art_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_product')),
                ('buyer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_user')),
                ('seller_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_shops')),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_Time', models.CharField(default='', max_length=300)),
                ('App_Date', models.CharField(default='', max_length=300)),
                ('App_Link', models.CharField(default='', max_length=300)),
                ('App_Status', models.CharField(default='', max_length=300)),
                ('App_Doctor_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_doctor')),
                ('App_User_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=30)),
                ('payment', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=30)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('cart_id', models.CharField(default='', max_length=30)),
                ('unit_id', models.CharField(default='', max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='order_item_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(default='', max_length=30)),
                ('date', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
                ('payment_status', models.CharField(default='', max_length=30)),
                ('worker_email', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_cart')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.order_tb')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_product')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_shops')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedhaApp.tbl_user')),
            ],
        ),
    ]
